### ISSUE TITLE
Issue: Patch Operation on a group is removing all the users and groups

### ISSUE THREAD

**Issue by de-jaina** [mick2004/nested-aad-scim-connector#5]
### **Description:**
I was trying to use the patch_dbgroup method to patch the Databricks group from the Active directory, but it is removing all the members from that group instead of removing the selected members.

### **To Replicate:**
1. Create a group in AAD.
2. Add 2 members in the group in AAD.
3. Execute the code. It will sync the Group and the members from AAD to Databricks Account.
4. Remove one member from the group in AAD.
5. Execute the code again to sync, but this time the group get empty. All the members from the group are getting removed.

### **What I tried:**
I tried changing the schema to urn:ietf:params:scim:api:messages:2.0:PatchOp by referring databricks api doc for [Azure](https://docs.databricks.com/api/azure/account/accountgroups/patch), but it still does not work.

Also, I found one [documentation ](https://api-docs.databricks.com/rest/latest/identity-federated-workspaces-scim-api.html)from databricks that states: Group membership cannot be updated through PATCH/PUT requests.

**### Other Issue:**
There is a minor issue in the databricks_client.py file:
obj["value"] = member["value"]
UnboundLocalError: local variable 'obj' referenced before assignment

obj = dict() is missing at line no. 131.

@mick2004 , @AbhiDatabricks

**Comment by mick2004** [comment]
Thanks @de-jaina I will have a look on this coming weekend.Feel free to open a pr if you wish .

**Comment by mick2004** [comment]
@all-contributors please add @jaina15  for test

**Comment by mick2004** [comment]
@all-contributors please add @jaina15 for test

**Comment by mick2004** [comment]
Fixed as part of https://github.com/mick2004/nested-aad-scim-connector/commit/0826ba88775e758f87e28d3bedb2fe24125f26ff . new release 0.1.4 released
